### ISSUE TITLE
执行数据预处理命令的第一条报错

### ISSUE THREAD

**Issue by catherie** [zzzkk2009/casia-surf-2019-codes#11]
(mxnet) zhao@zhao-PC:~/PycharmProjects/casia-surf-2019-codes$ python data_preprocess.py
usage: data_preprocess.py [-h] [--no-enmfake] [--aug] train
data_preprocess.py: error: the following arguments are required: train

**Comment by xjhjinhui** [comment]
> (mxnet) zhao@zhao-PC:~/PycharmProjects/casia-surf-2019-codes$ python data_preprocess.py
> usage: data_preprocess.py [-h] [--no-enmfake] [--aug] train
> data_preprocess.py: error: the following arguments are required: train

请问你有官方数据集中的验证集吗？
