### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by niezq** [zzzkk2009/casia-surf-2019-codes#3]
你好，数据集格式是怎么样的，或者您能分享您的数据集吗

**Comment by zzzkk2009** [comment]
https://competitions.codalab.org/competitions/20853
需要在官方网站注册并发邮件验证身份信息，官方才会提供下载链接，我这边没有权限，不好意思了。

**Comment by catherie** [comment]
你好 我注册之后还是没有下载链接

**Comment by Momotyust** [comment]
@catherie 请问，注册之后，你现在有下载到数据集吗？我也想下载这个数据集

**Comment by catherie** [comment]
> @catherie 请问，注册之后，你现在有下载到数据集吗？我也想下载这个数据集

需要给数据集所有者发一封邮件 在那个链接里面有

**Comment by xjhjinhui** [comment]
> https://competitions.codalab.org/competitions/20853
> 需要在官方网站注册并发邮件验证身份信息，官方才会提供下载链接，我这边没有权限，不好意思了。

您好，这个网站挂了，请问还有其他方式获取数据集吗
